[
    {
        "item_id":"41003",
        "item_quantity":"1",
        "item_size_id":"2",
        "item_addon": [
            {
                "addon_group_id":"1",
                "addon_items_array":[],
                "addon_group_price":0
            },
            {
                "addon_group_id":"2",
                "addon_items_array":["48015"],
                "addon_group_price":30
            }
        ]
    },
    {
        "item_id":"42001",
        "item_quantity":"1",
        "item_size_id":"4",
        "item_addon":[
            {
                "addon_group_id":"5",
                "addon_items_array":[],
                "addon_group_price":0
            }
        ]
    },
    {
        "item_id":"42006",
        "item_quantity":"1",
        "item_size_id":"4",
        "item_addon":[
            {
                "addon_group_id":"5",
                "addon_items_array":[],
                "addon_group_price":0
            }
        ]
    },
    {
        "item_id":"43003",
        "item_quantity":"1",
        "item_size_id":"5",
        "item_addon":""
    }
]